fix(icons): correct handling of tailwind prefix
rocketclimb/rocketicons pull request #146
Opened 2024-07-26 15:40 UTC by programad

The idea here is to add the prefix to the classes before sending them to the style generator.

This should fix #145

2024-07-26 17:04 UTC, amorimjj requested changes
Well done! Just few comments

2024-07-26 17:04 UTC, amorimjj commented on packages/tailwind/src/utils/config-handler.ts
> +  const prefixToAdd = prefix ? prefix : "";
We can move the initialization of the prefix to line 52 change it to `prefix: string = ''` and use the prefix across the code, avoiding to create this new variable

2024-07-26 17:04 UTC, amorimjj commented on packages/tailwind/src/utils/config-handler.ts
> +      ...AVAILABLE_VARIANTS.map((variant) => toColorsStyles(parsedColors, variant, prefixToAdd))
The suggestion above is because it's a little bit hard to understand how, why and where prefix became prefixToAdd

2024-07-26 17:04 UTC, amorimjj commented on packages/tailwind/src/utils/config-handler.ts
> +          styles: () => `${sanitize(theme.sizes[size])}`
Not sure, but I don't think the "`" is needed here. I think is safe to remove even from line 73 as well.

2024-09-03 18:35 UTC, programad commented
> Hi, any updates on this PR?

Almost there, sorry for the delay.

2024-09-09 19:48 UTC, merged